config/routes.rb
Gitlab::Application.routes.draw do
    namespace :admin do
        resources :users
        resources :projects
        resources :team_members

        get 'emails', :to => 'mailer#preview'

        get 'mailer/preview_note'
        get 'mailer/preview_user_new'
        get 'mailer/preview_issue_new'

        root :to => "users#index"
    end

    get "profile/password", :to => "profile#password"
    get "profile/password", :to => "profile#password_update"

    get "profile", :to => "profile#show"

    # get "profile/:id", :to => "profile#show"

    resources :projects, :only => [:new, :create, :index]
    resources :keys

    devise_for :users

    resources :projects, :except => [:new, :create, :index], :path => "/" do
        member do
            get "tree"
            get "blob"
            get "team"
            get "wall"

            # visualizador de tree
            get "tree/:commit_id" => "projects#tree"
            get "tree/:commit_id/:path" => "projects#tree",

            :as => :tree_file,

            :constraints => {
                :id => /[a-zA-Z0-9]+/,
                :commit_id => /[a-zA-Z0-9]+/,
                :path => /.*/
            }
        end

        resources :commits
        resources :team_members
        resources :issues
        resources :notes, :only => [:create, :destroy]
    end

    root :to => "projects#index"
end

app/models/ability.rb
class Ability
    def self.allowed(object, subject)
        case subject.class.name
        
        when "projeto" then project_abilities(object, subject)
            else []
        end
    end

    def self.project_abilities(user, project)
        rules = []

        rules << [
            :read_project,
            :read_issue,
            :read_team_member,
            :read_note
        ] if project.readers.include?(user)

        rules << [
            :write_project,
            :write_issue,
            :write_note
        ] if project.writers.include?(user)

        rules << [
            :admin_project,
            :admin_issue,
            :admin_team_member,
            :admin_note
        ] if project.admins.include?(user)

        rules.flatten
    end
end

app/models/users_project.rb
class UsersProject < ActiveRecord::Base
    belongs_to :user
    belongs_to :project

    attr_protected :project_id, :project

    after_commit :update_gitosis_project

    validates_uniqueness_of :user_id, :scope => [:project_id]

    validates_presence_of :user_id
    validates_presence_of :project_id

    delegate :name, :email, :to => :user, :prefix => true

    def update_gitosis_project
        Gitosis.new.configure do |c|
            c.update_project(project.path, project.gitosis_writers)
        end
    end
end

# == informação de schema
#
# nome da tabela: users_projects
#
# id         :integer   não nulo, chave primária
# user_id    :integer   não nulo
# project_id :integer   não nulo
#
# read       :boolean   padrão(false)
# write      :boolean   padrão(false)
# admin      :boolean   padrão(false)
#
# created_at :datetime
# updated_at :datetime

app/controllers/keys_controller.rb
class KeysController < ApplicationController
    respond_to :js

    def index
        @keys = current_user.keys.all

        respond_to do |format|
            format.html # index.html.erb
            format.json { render json: @keys }
        end
    end

    def new
        @key = current_user.keys.new

        respond_with(@key)
    end

    def create
        @key = current_user.keys.new(params[:key])
        @key.save

        respond_with(@key)
    end

    # delete /keys/1
    # delete /keys/1.json
    def destroy
        @key = current_user.keys.find(params[:id])
        @key.destroy

        respond_to do |format|
            format.html { redirect_to keys_url }
            format.js { render :nothing => true }
            format.json { head :ok }
        end
    end
end

app/helpers/application_helper.rb
require 'digest/md5'

module ApplicationHelper
    def gravatar_icon(user_email)
        "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user_email)}?s=40&d=identicon"
    end

    def commit_name(project, commit)
        if project.commit.id == commit.id
            "master"
        else
            commit.id
        end
    end

    def admin_namespace?
        controller.class.name.split("::").first=="admin"
    end

    def projects_namespace?
        !current_page?(root_url) &&
            controller.controller_name != "keys" &&
            !admin_namespace?
    end

    def last_commit(project)
        if project.repo_exists?
            time_ago_in_words(project.commit.committed_date) + " atrás"
        else
            "nunca"
        end
    end

    def search_autocomplete_source
        projects = current_user.projects.map{ |p| { :label => p.name, :url => project_path(p) } }

        default_nav = [
            { :label => "chaves", :url => keys_path },
            { :label => "projetos", :url => projects_path },
            { :label => "admin", :url => admin_root_path }
        ]

        project_nav = []

        if @project && !@project.new_record?
            project_nav = [
                { :label => "#{@project.code} / issues", :url => project_issues_path(@project) }, 
                { :label => "#{@project.code} / wall", :url => wall_project_path(@project) }, 
                { :label => "#{@project.code} / tree", :url => tree_project_path(@project) }, 
                { :label => "#{@project.code} / commits", :url => project_commits_path(@project) }, 
                { :label => "#{@project.code} / time", :url => team_project_path(@project) }
            ]
        end

        [projects, default_nav, project_nav].flatten.to_json
    end

    def handle_file_type(file_name, mime_type)
        if file_name =~ /(\.rb|\.ru|\.rake|Rakefile|\.gemspec|\.rbx|Gemfile)$/
            :ruby
        elsif file_name =~ /\.py$/
            :python
        elsif file_name =~ /(\.pl|\.scala|\.c|\.cpp|\.java|\.haml|\.html|\.sass|\.scss|\.xml|\.php|\.erb)$/
            $1[1..-1].to_sym
        elsif file_name =~ /\.js$/
            :javascript
        elsif file_name =~ /\.sh$/
            :bash
        elsif file_name =~ /\.coffee$/
            :coffeescript
        elsif file_name =~ /\.yml$/
            :yaml
        elsif file_name =~ /\.md$/
            :minid
        else
            :text
        end
    end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/keys_helper.rb
module KeysHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/team_members_helper.rb
module TeamMembersHelper
end

app/views/commits/_index.html.haml
= form_tag project_commits_path(@project), :method => :get do
    %h3
        = @project.name
        [ #{select_tag "branch", options_for_select(@repo.heads.map(&:name), @branch), :onchange => "this.form.submit();", :class => "small"} ]

= link_to 'voltar', project_path(@project), :class => "button"

%h1 listando commits

%div{:id => dom_id(@project)}
    = render "commits"

%br/

app/views/commits/index.js.erb
$("#more-commits-link").remove();

$('#<%= dom_id(@project)%>').append('<%= escape_javascript(render("commits")) %>');

app/views/layout/_flash.html.haml
- if alert || notice
    - text = alert || notice

    %div{:style => "display: none;", :id => "flash_container"}
        .container
            %center
                %h4= text

    :javascript
        $(function () {
            $("#flash_container").slideDown("slow");

            $("#flash_container").click(function () {
                $(this).slideUp("slow");
            });

            setTimeout("hideFlash()", 2000);
        });

        function hideFlash() {
            $("#flash_container").slideUp("slow");
        }

app/views/layout/_head_panel.html.erb
<div id="header-panel">
    <div class="container">
        <div class="span-24">
            <div class="span-10">
                <%#= image_tag "git.png", :height => 40, :class => "left" %>
                <%#= link_to "gitlab", root_path, :id => "logo" %>

                <span class="search-holder">
                    <%= text_field_tag "search", nil, :placeholder => "pesquisar" %>
                </span>
            </div>

            <div class="right">
                <%= link_to truncate(@project.name, :length => 20), project_path(@project), :class => "current button" if @project && !@project.new_record? %>
                <%= link_to 'home', root_path, :class => current_page?(root_url) ? "current button" : "button" %>
                <%= link_to 'projetos', projects_path, :class => current_page?(projects_path) ? "current button" : "button" %>
                <%= link_to 'perfil', profile_path, :class => (controller.controller_name == "keys") ? "current button" : "button" %>
                <%= link_to('admin', admin_root_path, :class => admin_namespace? ? "current button" : "button" ) if current_user.is_admin? %>

                <%#= link_to 'perfil', edit_user_registration_path, :class => "button" %>
                <%= link_to 'deslogar', destroy_user_session_path, :class => "button", :method => :delete %>
            </div>
        </div>
    </div>
</div>

<% if current_user %>
    <%= javascript_tag do %>
        $(function() {
            $("#search").autocomplete({
                source: <%= raw search_autocomplete_source %>,
                
                select: function(event, ui) { location.href = ui.item.url }
            });
        });
    <% end %>
<% end %>

app/views/layout/notify.html.haml
%html{:lang => "en"}
    %head
        %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}
            %title
                underneath
            :css
                .header h1 {color: #BBBBBB !important; font: bold 32px Helvetica, Arial, sans-serif; margin: 0; padding: 0; line-height: 40px;}
                .header p {color: #c6c6c6; font: normal 12px Helvetica, Arial, sans-serif; margin: 0; padding: 0; line-height: 18px;}
                
                .content h2 {color:#646464 !important; font-weight: bold; margin: 0; padding: 0; line-height: 26px; font-size: 18px; font-family: Helvetica, Arial, sans-serif;}
                .content p {color:#767676; font-weight: normal; margin: 0; padding: 0; line-height: 20px; font-size: 12px;font-family: Helvetica, Arial, sans-serif;}
                .content a {color: #0eb6ce; text-decoration: none;}

                .footer p {font-size: 11px; color:#7d7a7a; margin: 0; padding: 0; font-family: Helvetica, Arial, sans-serif;}
                .footer a {color: #0eb6ce; text-decoration: none;}

        %body{:bgcolor => "#EAEAEA", :style => "margin: 0; padding: 0; background: #EAEAEA;"}
            %table{:align => "center", :border => "0", :cellpadding => "0", :cellspacing => "0", :style => "padding: 35px 0; background: #EAEAEA;", :width => "100%"}
                %tr
                    %td{:align => "center", :style => "margin: 0; padding: 0; background: #EAEAEA;"}
                        %table.header{:align => "center", :border => "0", :cellpadding => "0", :cellspacing => "0", :style => "font-family: Helvetica, Arial, sans-serif; background: #333;", :width => "600"}
                            %tr
                                %td{:style => "font-size: 0px;", :width => "20"}
                                    \
                                %td{:align => "left", :style => "padding: 18px 0 10px;", :width => "580"}
                                    %h1{:style => "color: #BBBBBB; font: normal 32px Helvetica, Arial, sans-serif; margin: 0; padding: 0; line-height: 40px;"}
                                        underneath
                                        - if @project
                                            | #{@project.name}

                        %table{:align => "center", :bgcolor => "#fff", :border => "0", :cellpadding => "0", :cellspacing => "0", :style => "font-family: Helvetica, Arial, sans-serif; background: #fff;", :width => "600"}
                            %tr= yield
                            
                            %tr
                                %tr{:align => "left", :colspan => "2", :height => "3", :style => "padding: font-size: 0; line-height: 0; height: 3px;", :width => "600"}

                        %table.footer{:align => "center", :border => "0", :cellpadding => "0", :cellspacing => "0", :style => "font-family: Helvetica, Arial, sans-serif; line-height: 10px;", :width => "600"}
                            %tr
                                %td{:align => "center", :style => "padding: 5px 0 10px; font-size: 11px; color:#7d7a7a; margin: 0; line-height: 1.2;font-family: Helvetica, Arial, sans-serif;", :valign => "top"}
                                    %br
                                        %p{:style => "font-size: 11px; color:#7d7a7a; margin: 0; padding: 0; font-family: Helvetica, Arial, sans-serif;"}
                                            você está recebendo esse newsletter porque você está no time do projeto.